apiVersion: v1
kind: Service
metadata:
  name: backend-service      # Name of the Service
  labels:
    app: backend             # Label for identifying the Service
spec:
  selector:
    app: backend             # This should match the labels of your backend Pods
  ports:
    - port: 3001             # Port exposed by the Service
      targetPort: 3001       # Port on the backend container
      nodePort: 30001        # Specify a NodePort for external access (range: 30000-32767)
  type: NodePort             # Change to NodePort to allow external access

