apiVersion: v1
kind: Service
metadata:
  name: frontend-service      # Name of the Service
  labels:
    app: frontend             # Label for identifying the Service
spec:
  selector:
    app: frontend             # This should match the labels of your frontend Pods
  ports:
    - port: 3000              # Port exposed by the Service
      targetPort: 3000        # Port on the frontend container
      nodePort: 30002         # Optional: Specify a NodePort for external access
  type: NodePort              # Change to NodePort to allow external access

