apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo
spec:
  type: NodePort       # Set the Service type to NodePort
  selector:
    app: mongo         # This should match the labels of your MongoDB Pods
  ports:
    - port: 27017      # Port exposed by the Service
      targetPort: 27017 # Port on the MongoDB container
      nodePort: 30000  # Optional: Specify a port number in the range 30000-32767

